--- 
- hosts: localhost
  connection: local
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "ansible-kp"
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        aws_access_key: "{{aws_access_key}}"  # From ansible-vault
        aws_secret_key: "{{aws_secret_key}}"  # From ansible-vault    
        network_interfaces:
          - assign_public_ip: true
        image_id: "{{ item.image }}"
      loop: 
        - { image: "ami-01816d07b1128cd2d", name: manage-node-1 } # Amazon Linux 2023 AMI (HVM), SSD Volume Type
        - { image: "ami-0e2c8caa4b6378d8c", name: manage-node-2 } # Ubuntu Server 24.04 LTS (HVM), SSD Volume Type
        - { image: "ami-0e2c8caa4b6378d8c", name: manage-node-3 } # Ubuntu Server 24.04 LTS (HVM), SSD Volume Type
  